Future/add base page
n-chornyi/bookstore-666 pull request #1
Opened 2021-12-15 23:55 UTC by n-chornyi

2021-12-16 15:43 UTC, gremax requested changes

2021-12-16 15:43 UTC, gremax commented on app/controllers/billing_addresses_controller.rb
> +    billing.save
You should create entities using user's association, for instance
```
address = current_user.build_billing_address(billing_params)

if address.save
else
end
```

2021-12-16 15:43 UTC, gremax commented on app/controllers/billing_addresses_controller.rb
> +    redirect_to '/settings', alert: 'Billing address update!'
use rails routes helper instead, `settings_path`, etc

2021-12-16 15:43 UTC, gremax commented on app/controllers/billing_addresses_controller.rb
> +    BillingAddress.update(billing_params)
what you're trying to update here? you need to find billing address first by id

2021-12-16 15:43 UTC, gremax commented on app/controllers/billing_addresses_controller.rb
> +    redirect_to '/settings', alert: 'Billing address update!'
use rails routes helper

2021-12-16 15:43 UTC, gremax commented on app/controllers/books_controller.rb
> +require 'pagy'
do we need this `require` here? I think pagy is required by default

2021-12-16 15:43 UTC, gremax commented on app/controllers/books_controller.rb
> +    @pagy, @books = pagy(Book.all.where(category_id: @current_category.id).order(get_sort_type)) if @current_category.id.present?
you should move all these book-related things to the Book model as a scope or new class methods
if you have a current category, why you don't use relation `@current_category.books` 

also avoid to use `get_` and `set_` in your method names

2021-12-16 15:43 UTC, gremax commented on app/controllers/books_controller.rb
> +    @book = Book.find_by(id: params[:id])
you can use `#find` instead of `#find_by`

2021-12-16 15:43 UTC, gremax commented on app/controllers/books_controller.rb
> +    @description = @book.description.slice(100, @book.description.length - 100)
move description shorteners to instance method of the Book model

2021-12-16 15:43 UTC, gremax commented on app/controllers/books_controller.rb
> +    @current_category = Category.find_by(id: params[:category_id]) || Category.new(id: nil, name: nil)
why do you need empty Category?

2021-12-16 15:43 UTC, gremax commented on config/initializers/constant.rb
> +TYPES_SORT = { newest_first:       { name: 'Newest first', query: 'created_at DESC' },
This should be defined in Category model

2021-12-16 15:43 UTC, gremax commented on app/controllers/books_controller.rb
> +  end
let's think how we can refactor this and move out of controller

2021-12-16 15:43 UTC, gremax commented on app/controllers/home_controller.rb
> +    @last_book = Book.last(3)
TODO: move to the Book model needed scopes

2021-12-16 15:43 UTC, gremax commented on app/controllers/settings_controller.rb
> +  before_action :set_user
avoid to use `set_` and `get_` prefixes, I believe `load_user` would be great option

2021-12-16 15:43 UTC, gremax commented on app/controllers/settings_controller.rb
> +    @billing = BillingAddress.find_by(user_id: current_user.id) || BillingAddress.new(user_id: current_user.id)
Why not like
```
current_user.shipping_address
```

and you can overwrite `#shipping_address` for user to return persisted object or new one

or

```
current_user.billing_address || current_user.build_billing_address
```

Use associations!

2021-12-16 15:43 UTC, gremax commented on app/controllers/settings_controller.rb
> +    if @user.update_without_password(user_params)
this method name looks strange

2021-12-16 15:43 UTC, gremax commented on app/controllers/shipping_addresses_controller.rb
> +  end
the same as above for BillingAddresssesController

2021-12-16 15:43 UTC, gremax commented on app/helpers/application_helper.rb
> +  end
I think helper is not correct place to store logic like this

2021-12-16 15:43 UTC, gremax commented on app/helpers/books_helper.rb
> +    book.authors.map { |author| "#{author.first_name} #{author.last_name}" }.join(', ')
play around with `.pluck`, map is not a good idea

2021-12-16 15:43 UTC, gremax commented on app/models/user.rb
> +    user = User.where(email: auth.info.email).first
why not
```
self.find_by(email: '')
```
?

2021-12-16 15:43 UTC, gremax commented on app/views/application/_category.html.haml
> +    = link_to "#{category.name}", catalog_path(category_id: category.id)
redundant interpolation, also you can use catalog_path(category) instead

2021-12-16 15:43 UTC, gremax commented on app/views/application/_footer.html.haml
> +              %i.fa.fa-instagram{'aria-hidden': "true"}
no new line

2021-12-16 15:43 UTC, gremax commented on app/views/books/_sort_by.html.haml
> +      = link_to option[:name], catalog_path(category_id: @current_category.id, sort_by: type)
catalog_path(@current_category, sort_by: type)

2021-12-16 15:43 UTC, gremax commented on app/views/books/index.html.haml
> +          = link_to catalog_path(category_id: "#{category.id}"), class: "filter-link #{'active' if category.id == @current_category.id}" do
why do we need interpolation here?

2021-12-16 15:43 UTC, gremax commented on config/initializers/pagy.rb
> +# Pagy initializer file (5.6.6)
Try to avoid adding redundant comments

2021-12-16 15:43 UTC, gremax commented on spec/factories/authors.rb
> +require 'ffaker'
I believe you can require ffaker just once in rails_helper

2021-12-16 21:31 UTC, n-chornyi commented on Gemfile
> +#gem 'rubocop-performance', '~> 0.0.1'
+

2021-12-16 21:32 UTC, n-chornyi commented on app/admin/authors.rb
> +  #
+

2021-12-16 21:36 UTC, n-chornyi commented on app/controllers/billing_addresses_controller.rb
> +    billing.save
+

2021-12-16 21:37 UTC, n-chornyi commented on app/controllers/billing_addresses_controller.rb
> +    redirect_to '/settings', alert: 'Billing address update!'
+

2021-12-16 21:39 UTC, n-chornyi commented on app/controllers/billing_addresses_controller.rb
> +    BillingAddress.update(billing_params)
+

2021-12-16 21:39 UTC, n-chornyi commented on app/controllers/billing_addresses_controller.rb
> +    redirect_to '/settings', alert: 'Billing address update!'
+

2021-12-16 21:40 UTC, n-chornyi commented on app/controllers/books_controller.rb
> +require 'pagy'
+

2021-12-16 21:42 UTC, n-chornyi commented on app/controllers/books_controller.rb
> +    @book = Book.find_by(id: params[:id])
+

2021-12-16 21:44 UTC, n-chornyi commented on app/controllers/books_controller.rb
> +    @description = @book.description.slice(100, @book.description.length - 100)
+

2021-12-16 22:07 UTC, n-chornyi commented on app/controllers/settings_controller.rb
> +  before_action :set_user
+

2021-12-16 22:08 UTC, n-chornyi commented on app/controllers/settings_controller.rb
> +    @billing = BillingAddress.find_by(user_id: current_user.id) || BillingAddress.new(user_id: current_user.id)
+

2021-12-17 08:58 UTC, n-chornyi commented on app/views/application/_footer.html.haml
> +              %i.fa.fa-instagram{'aria-hidden': "true"}
+

2021-12-17 09:01 UTC, n-chornyi commented on config/initializers/pagy.rb
> +# Pagy initializer file (5.6.6)
+

2021-12-17 09:19 UTC, n-chornyi commented on spec/factories/authors.rb
> +require 'ffaker'
+

2021-12-17 11:28 UTC, n-chornyi commented on app/controllers/books_controller.rb
> +    @pagy, @books = pagy(Book.all.where(category_id: @current_category.id).order(get_sort_type)) if @current_category.id.present?
+-

2021-12-17 11:35 UTC, n-chornyi commented on app/controllers/books_controller.rb
> +    @current_category = Category.find_by(id: params[:category_id]) || Category.new(id: nil, name: nil)
+

2021-12-17 13:00 UTC, n-chornyi commented on app/controllers/home_controller.rb
> +    @last_book = Book.last(3)
+

2021-12-17 21:05 UTC, n-chornyi commented on app/views/books/index.html.haml
> +          = link_to catalog_path(category_id: "#{category.id}"), class: "filter-link #{'active' if category.id == @current_category.id}" do
+

2021-12-17 21:05 UTC, n-chornyi commented on app/views/books/_sort_by.html.haml
> +      = link_to option[:name], catalog_path(category_id: @current_category.id, sort_by: type)
+

2021-12-17 21:06 UTC, n-chornyi commented on app/views/application/_category.html.haml
> +    = link_to "#{category.name}", catalog_path(category_id: category.id)
+

2021-12-17 21:08 UTC, n-chornyi commented on app/models/user.rb
> +    user = User.where(email: auth.info.email).first
+

2021-12-17 21:09 UTC, n-chornyi commented on app/helpers/books_helper.rb
> +    book.authors.map { |author| "#{author.first_name} #{author.last_name}" }.join(', ')
-

2021-12-17 21:09 UTC, n-chornyi commented on app/helpers/application_helper.rb
> +  end
+

2021-12-17 21:09 UTC, n-chornyi commented on app/controllers/shipping_addresses_controller.rb
> +  end
+

2021-12-17 21:22 UTC, n-chornyi commented on config/initializers/constant.rb
> +TYPES_SORT = { newest_first:       { name: 'Newest first', query: 'created_at DESC' },
+-

2021-12-17 21:22 UTC, n-chornyi commented on app/controllers/books_controller.rb
> +  end
+-

2021-12-22 13:29 UTC, gremax requested changes

2021-12-22 13:29 UTC, gremax commented on app/controllers/billing_addresses_controller.rb
> +    billing.save ? flash[:alert] = 'Billing address update' : flash[:alert] = 'Error update billing address'
avoid to use ternary operator

2021-12-22 13:29 UTC, gremax commented on app/controllers/billing_addresses_controller.rb
> +    redirect_to settings_path
Why here is redirect? What about validation?

2021-12-22 13:29 UTC, gremax commented on app/controllers/billing_addresses_controller.rb
> +    billing.update(billing_params)
What about form validation?

2021-12-22 13:29 UTC, gremax commented on app/controllers/books_controller.rb
> +  before_action :order_item, only: %i[show]
What does mean `:order_item`, would be better to name the method as an action like `load_order_item`?
`only: :show`
It looks like you should not use callback action, u need order item only in one `#show` action

2021-12-22 13:29 UTC, gremax commented on app/controllers/cart_controller.rb
> +  before_action :order, only: %i[index]
again, what does mean this method name? Why order loading is extracted to callback? Is there another actions except index?

2021-12-22 13:29 UTC, gremax commented on app/controllers/cart_controller.rb
> +  end
This should be moved to Order, why is this logic here?

2021-12-22 13:29 UTC, gremax commented on app/controllers/cart_controller.rb
> +
You have to move these assignments to the order object

2021-12-22 13:29 UTC, gremax commented on app/controllers/catalog_controller.rb
> +    @pagy, @books = pagy(Book.all.order(sort_type(params[:sort_by])))
move order logic to Book class method

2021-12-22 13:29 UTC, gremax commented on app/controllers/catalog_controller.rb
> +    @pagy, @books = pagy(Category.find(params[:id]).books.order(sort_type(params[:sort_by])))
too many brackets, use variables, move order to Book class

2021-12-22 13:29 UTC, gremax commented on app/controllers/order_items_controller.rb
> +  before_action :check_order, only: %i[create]
I don't think you need this callback. What it does

2021-12-22 13:29 UTC, gremax commented on app/controllers/order_items_controller.rb
> +    order_item = OrderItem.find_or_create_by!(book_id: params[:order_item][:book_id], order_id: @current_order_id)
use `#order_item_params` to get id, load current order and create order_item through association

2021-12-22 13:29 UTC, gremax commented on app/controllers/order_items_controller.rb
> +    order_item.count += params[:order_item][:count].to_i
use permitted params

2021-12-22 13:29 UTC, gremax commented on app/controllers/reviews_controller.rb
> +    review.user_id = current_user.id
please, use associations

2021-12-22 13:29 UTC, gremax commented on app/controllers/shipping_addresses_controller.rb
> +    redirect_to settings_path, alert: 'Shipping address update!'
associations

2021-12-22 13:29 UTC, gremax commented on app/helpers/application_helper.rb
> +  include OrdersHelper
you don't need this inclusion

2021-12-22 13:29 UTC, gremax commented on app/controllers/catalog_controller.rb
> +  include CatalogHelper
you don't need this inclusion

2021-12-22 13:29 UTC, gremax commented on app/controllers/cart_controller.rb
> +  include OrdersHelper
you don't need this inclusion

2021-12-22 13:29 UTC, gremax commented on app/helpers/orders_helper.rb
> +module OrdersHelper
really duplicated methods, move this to ApplicationController as memoized `#current_order` method

2021-12-22 13:29 UTC, gremax commented on app/models/billing_address.rb
> +  has_many :orders, dependent: :destroy
This looks strange, should we remove orders if we remove billing address?

2021-12-22 13:29 UTC, gremax commented on app/models/book.rb
> +  has_many :authors, through: :authorships, dependent: :destroy
This looks strange, should we remove authors if we remove book?

2021-12-22 13:29 UTC, gremax commented on app/models/book.rb
> +  has_many :order_id, dependent: :destroy
what is order_id

2021-12-22 13:29 UTC, gremax commented on app/models/book.rb
> +
where is the logic for top books scope
for what stands `.last_books`? I mean what if we changed order somewhere?

2021-12-22 13:29 UTC, gremax commented on app/models/category.rb
> +  has_many :books, dependent: :destroy
Should we remove books with the category?

2021-12-22 13:29 UTC, gremax commented on app/models/credit_card.rb
> +  has_many :orders, dependent: :destroy
should we remove orders with CC?

2021-12-22 13:29 UTC, gremax commented on app/models/discount.rb
> +  scope :amount_discount, ->(code) { Discount.find_by(code: code) }
It's not a scope actually, move to the method

2021-12-22 13:29 UTC, gremax commented on app/models/order.rb
> +  scope :current_active_order_guest, ->(id) { find_or_create_by!(id: id, state: 0) }
do you understand for what you should use scope? it's wrong place to implement logic like this

2021-12-22 13:29 UTC, gremax commented on app/models/shipping_address.rb
> +  has_many :orders, dependent: :destroy
so if I remove shipping address, orders will be removed as well?

2022-01-11 14:00 UTC, gremax commented on app/views/books/_review.html.haml
> +- all_reviews.each do |review|
should be moved into `app/views/reviews/`

2022-01-11 14:03 UTC, gremax commented on app/views/books/show.html.haml
> +        = form_for OrderItem.new, method: :post do |form|
Could you build this order item for needed book and current user in controller?

2022-01-11 14:04 UTC, gremax commented on app/views/books/show.html.haml
> +          %p.lead.small.pull-right #{@book.publication_year}
why interpolation?

2022-01-11 14:04 UTC, gremax commented on app/views/books/show.html.haml
> +          %p.lead.small.pull-right #{@book.materials}
why interpolation?

2022-01-11 14:05 UTC, gremax commented on app/views/carts/_order_items.html.haml
> +- order.each do |item|
`order.each` ? if it is a collection, local variable should be named as `orders`

2022-01-11 14:05 UTC, gremax commented on app/views/books/show.html.haml
> +    = render 'review', all_reviews: @review
why `@review` if it is a collection?

2022-01-11 14:07 UTC, gremax commented on app/views/carts/_order_items_mobile.html.haml
> +          %span.font-16.in-gold-500= number_to_currency(item.book.show_price * item.count,  unit: "€")
`item.book.show_price * item.count` should be moved to order item object across all the store

2022-01-11 14:09 UTC, gremax commented on app/views/carts/show.html.haml
> +              = text_field_tag(:code, nil, placeholder: 'Enter Your Coupon Code', class: 'form-control mb-30', value: "#{@current_order.code_discount if @current_order.code_discount}")
what if @current_order.code_discount is an empty string? As I saw previously you're saving empty string as discount code

2022-01-11 14:12 UTC, gremax commented on app/views/checkouts/complete.html.haml
> +    - @current_order.order_items.each_with_index do |item, index|
Can't find where you're using index here

2022-01-11 14:13 UTC, gremax commented on app/views/checkouts/confirm.html.haml
> +%main.container.general-main-wrap
this view is the same as previous steps, why don't split them using partials? Don't repeat yourself (DRY)

2022-01-11 14:15 UTC, gremax commented on app/views/home/_bestseller.html.haml
> +      %p.lead.small= book.all_authors
It seems I already saw this code before twice, should you use `_book` partial for these places?

2022-01-11 14:17 UTC, gremax commented on app/views/orders/show.html.haml
> +          %tr
3rd time I see this haml, DRY

2022-01-11 14:18 UTC, gremax commented on config/initializers/devise.rb
> +# Assuming you have not yet modified this file, each configuration option below
Remove all comments here

2022-01-11 14:18 UTC, gremax commented on config/initializers/simple_form.rb
> +# Uncomment this and change the path if necessary to include your own
Remove comments

2022-01-11 14:59 UTC, gremax commented on app/controllers/application_controller.rb
> +      order.order_items&.each do |item|
order.order_items.update_all

2022-01-11 15:01 UTC, gremax commented on app/controllers/application_controller.rb
> +    order = Order.where(user_id: current_user.id).where.not(state: :complete).first
current_user.order.where.not(state: :complete).first_or_create ?

2022-01-11 21:46 UTC, n-chornyi commented on app/admin/discounts.rb
> +  # See permitted parameters documentation:
+

2022-01-11 21:46 UTC, n-chornyi commented on app/admin/reviews.rb
> +    permitted
+

2022-01-12 11:36 UTC, n-chornyi commented on app/assets/javascripts/checkout_handler.js
> +function edit_order_params(param) {
+

2022-01-12 11:37 UTC, n-chornyi commented on app/assets/javascripts/settings.js
> +    $("#checkbox_delete_account").click(function(){
+

2022-01-12 11:47 UTC, n-chornyi commented on app/assets/javascripts/show_book.js
> +    let temp_value = parseInt($("#quantity-input").val())
+

2022-01-12 15:46 UTC, n-chornyi commented on app/assets/javascripts/checkout_handler.js
> +        url: document.URL,
+

2022-01-12 15:46 UTC, n-chornyi commented on app/controllers/application_controller.rb
> +  before_action :move_order_items_after_sign_in
+

2022-01-13 12:10 UTC, n-chornyi commented on app/controllers/application_controller.rb
> +    order = Order.where(user_id: current_user.id).where.not(state: :complete).first
+

2022-01-13 12:10 UTC, n-chornyi commented on app/controllers/application_controller.rb
> +      order.order_items&.each do |item|
+

2022-01-13 12:40 UTC, n-chornyi commented on config/initializers/simple_form.rb
> +# Uncomment this and change the path if necessary to include your own
+

2022-01-13 12:47 UTC, n-chornyi commented on config/initializers/devise.rb
> +# Assuming you have not yet modified this file, each configuration option below
+

2022-01-13 12:48 UTC, n-chornyi commented on app/controllers/application_controller.rb
> +    end
+

2022-01-13 12:48 UTC, n-chornyi commented on app/controllers/application_controller.rb
> +  before_action :current_order
+

2022-01-13 15:11 UTC, n-chornyi commented on app/controllers/checkouts_controller.rb
> +    render "checkouts/#{edit_template_name}.html.haml"
+

2022-01-13 15:13 UTC, n-chornyi commented on app/controllers/carts_controller.rb
> +    discount = Discount.find_by(code: params[:code])
+

2022-01-13 21:39 UTC, n-chornyi commented on app/controllers/checkouts_controller.rb
> +    @deliveries ||= Delivery.all
+

2022-01-13 21:40 UTC, n-chornyi commented on app/controllers/checkouts_controller.rb
> +    @current_order = Order.create!(user_id: current_user.id) if @current_order.complete?
+

2022-01-13 21:45 UTC, n-chornyi commented on app/controllers/order_items_controller.rb
> +    order_item = OrderItem.find_or_create_by!(book_id: params[:order_item][:book_id], order_id: @current_order.id)
+

2022-01-13 21:49 UTC, n-chornyi commented on app/controllers/order_items_controller.rb
> +
+

2022-01-13 22:01 UTC, n-chornyi commented on app/controllers/order_items_controller.rb
> +      if order_item.count - 1 >= 1
+

2022-01-13 22:08 UTC, n-chornyi commented on app/controllers/order_items_controller.rb
> +        order_item.count = order_item.count - 1
+

2022-01-13 22:09 UTC, n-chornyi commented on app/controllers/order_items_controller.rb
> +      order_item = @current_order.order_items.find(params[:id])
+

2022-01-13 22:14 UTC, n-chornyi commented on app/controllers/order_items_controller.rb
> +      order_item = @current_order.order_items.find(params[:id])
+

2022-01-13 22:15 UTC, n-chornyi commented on app/controllers/order_items_controller.rb
> +      if order_item.count + 1 < 100
+

2022-01-13 22:16 UTC, n-chornyi commented on app/controllers/orders_controller.rb
> +    @orders ||= Order.where(user_id: current_user.id, state: :complete)
+

2022-01-13 22:16 UTC, n-chornyi commented on app/controllers/orders_controller.rb
> +    @show_order = Order.find_by(id: params[:id], user_id: current_user.id)
+

2022-01-13 22:25 UTC, n-chornyi commented on app/controllers/reviews_controller.rb
> +      flash[:danger] = review.errors.full_messages.join('. ').gsub('Text', 'Review')
+

2022-01-13 22:26 UTC, n-chornyi commented on app/controllers/settings_controller.rb
> +    @user = current_user
+

2022-01-13 22:29 UTC, n-chornyi commented on app/controllers/settings_controller.rb
> +  def find_billing_address
+

2022-01-13 22:30 UTC, n-chornyi commented on app/models/book.rb
> +  scope :last_books, -> { last(3) }
+

2022-01-13 22:47 UTC, n-chornyi commented on app/models/book.rb
> +  end
+

2022-01-13 22:47 UTC, n-chornyi commented on app/models/book.rb
> +  def self.types_sort
+

2022-01-13 22:50 UTC, n-chornyi commented on app/models/order.rb
> +    amount ||= Discount.find_by!(code: code_discount).amount if Discount.find_by(code: code_discount)
+

2022-01-13 23:31 UTC, n-chornyi commented on app/models/order.rb
> +    'Canceled' if canceled?
+

2022-01-13 23:38 UTC, n-chornyi commented on app/models/shipping_address.rb
> +end
+

2022-01-13 23:39 UTC, n-chornyi commented on app/views/application/_category.html.haml
> +    = link_to "#{category.name}", catalog_path(category)
+

2022-01-13 23:39 UTC, n-chornyi commented on app/views/books/_form_review.html.haml
> +        = f.button :submit, "Post", class: "btn btn-default mb-20 pull-right mb-55"
+

2022-01-13 23:39 UTC, n-chornyi commented on app/views/books/_review.html.haml
> +- all_reviews.each do |review|
+

2022-01-13 23:40 UTC, n-chornyi commented on app/views/books/show.html.haml
> +        = form_for OrderItem.new, method: :post do |form|
+

2022-01-13 23:41 UTC, n-chornyi commented on app/views/books/show.html.haml
> +          %p.lead.small.pull-right #{@book.publication_year}
+

2022-01-13 23:41 UTC, n-chornyi commented on app/views/books/show.html.haml
> +          %p.lead.small.pull-right #{@book.materials}
+

2022-01-13 23:42 UTC, n-chornyi commented on app/views/carts/_order_items.html.haml
> +- order.each do |item|
+

2022-01-13 23:45 UTC, n-chornyi commented on app/views/carts/show.html.haml
> +              = text_field_tag(:code, nil, placeholder: 'Enter Your Coupon Code', class: 'form-control mb-30', value: "#{@current_order.code_discount if @current_order.code_discount}")
---

2022-01-13 23:49 UTC, n-chornyi commented on app/views/carts/_order_items_mobile.html.haml
> +          %span.font-16.in-gold-500= number_to_currency(item.book.show_price * item.count,  unit: "€")
+

2022-01-13 23:51 UTC, n-chornyi commented on app/views/checkouts/complete.html.haml
> +    - @current_order.order_items.each_with_index do |item, index|
+

2022-01-14 10:41 UTC, n-chornyi commented on app/controllers/order_items_controller.rb
> +    up_count_book if request.request_method == 'PUT'
+

2022-01-14 10:53 UTC, n-chornyi commented on app/models/billing_address.rb
> +            format: { with: /\A[0-9\-]*\z/,
---

2022-01-14 11:10 UTC, n-chornyi commented on app/views/checkouts/confirm.html.haml
> +%main.container.general-main-wrap
+

2022-01-14 11:44 UTC, n-chornyi commented on app/views/home/_bestseller.html.haml
> +      %p.lead.small= book.all_authors
+++

2022-01-17 14:23 UTC, n-chornyi commented on app/controllers/carts_controller.rb
> +    end
+

2022-01-20 13:48 UTC, gremax requested changes

2022-01-20 13:48 UTC, gremax commented on app/assets/javascripts/toast.min.js
> +class Toast{constructor(t){this._title=!1!==t.title&&(t.title||"Title"),console.log(this._title),this._text=t.text||"Message...",this._theme=t.theme||"default",this._autohide=t.autohide&&!0,this._int
This file should be in vendor directory, shoud not be minificated

2022-01-20 13:48 UTC, gremax commented on app/assets/stylesheets/toast.min.css
> +:root{--toast-width:270px;--toast-border-radius:0.25rem;--toast-theme-default:#fff;--toast-theme-primary:#0d6efd;--toast-theme-secondary:#6c757d;--toast-theme-success:#198754;--toast-theme-danger:#dc
should be in vendor, not minificated

2022-01-20 13:48 UTC, gremax commented on app/controllers/reviews_controller.rb
> +  include ReviewHelper
you don't need this include

2022-01-20 13:48 UTC, gremax commented on app/models/book.rb
> +  end
?

2022-01-20 13:48 UTC, gremax commented on app/models/book.rb
> +  scope :last_books, -> { order('id').last(3) }
I think `:created_at` would be better

2022-01-20 13:48 UTC, gremax commented on app/models/book.rb
> +                .order('sum("order_items"."count") DESC').count.keys
useless quotes

2022-01-20 13:48 UTC, gremax commented on app/controllers/order_items_controller.rb
> +    if (order_item = current_order.order_items.find(params[:order_item_id])) && (order_item.count - 1).positive?
```
order_item = current_order.order_items.find(params[:order_item_id])
```
this can be moved to callback and loaded before down/up actions

2022-01-20 13:48 UTC, gremax commented on app/controllers/order_items_controller.rb
> +    if (order_item = current_order.order_items.find(params[:order_item_id])) && (order_item.count - 1).positive?
I'm not sure I understand what does mean
```
(order_item.count - 1).positive?
```

and

```
(order_item.count + 1 < 100)
```

If you need this check, you definitely should validates this in the model before you update the record

2022-01-20 13:48 UTC, gremax commented on app/views/checkouts/payment_form.html.haml
> +    = card.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }
why do you use old style of hash keys/values across views?

2022-01-20 13:48 UTC, gremax commented on config/spring.rb
> +  '.ruby-version',
you don't have to do this across standard files, you needed to unify style at least in your javascripts/views

2022-01-20 15:30 UTC, n-chornyi commented on config/spring.rb
> +  '.ruby-version',
+

2022-01-20 15:31 UTC, n-chornyi commented on app/views/checkouts/payment_form.html.haml
> +    = card.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }
+

2022-01-20 15:33 UTC, n-chornyi commented on app/models/book.rb
> +                .order('sum("order_items"."count") DESC').count.keys
+

2022-01-20 15:33 UTC, n-chornyi commented on app/models/book.rb
> +  scope :last_books, -> { order('id').last(3) }
+

2022-01-20 21:40 UTC, n-chornyi commented on app/assets/stylesheets/toast.min.css
> +:root{--toast-width:270px;--toast-border-radius:0.25rem;--toast-theme-default:#fff;--toast-theme-primary:#0d6efd;--toast-theme-secondary:#6c757d;--toast-theme-success:#198754;--toast-theme-danger:#dc
+

2022-01-20 21:41 UTC, n-chornyi commented on app/assets/javascripts/toast.min.js
> +class Toast{constructor(t){this._title=!1!==t.title&&(t.title||"Title"),console.log(this._title),this._text=t.text||"Message...",this._theme=t.theme||"default",this._autohide=t.autohide&&!0,this._int
+

2022-01-21 14:28 UTC, n-chornyi commented on app/controllers/reviews_controller.rb
> +  include ReviewHelper
+

2022-01-24 14:22 UTC, gremax requested changes

2022-01-24 14:22 UTC, gremax commented on app/controllers/order_items_controller.rb
> +    @load_order_item ||= current_order.order_items.find(params[:order_item_id])
It's not readable, you should set it like. Why do you need memo?
```ruby
  def load_order_item
    @order_item = current_order.order_items.find(params[:order_item_id])
  end
```

2022-01-24 14:22 UTC, gremax commented on vendor/assets/javascripts/toast.min.js
> +class Toast{constructor(t){this._title=!1!==t.title&&(t.title||"Title"),console.log(this._title),this._text=t.text||"Message...",this._theme=t.theme||"default",this._autohide=t.autohide&&!0,this._int
Should not be minified

2022-01-24 14:22 UTC, gremax commented on vendor/assets/stylesheets/toast.min.css
> +:root{--toast-width:270px;--toast-border-radius:0.25rem;--toast-theme-default:#fff;--toast-theme-primary:#0d6efd;--toast-theme-secondary:#6c757d;--toast-theme-success:#198754;--toast-theme-danger:#dc
Should not be minified

2022-01-24 14:43 UTC, n-chornyi commented on app/controllers/order_items_controller.rb
> +    @load_order_item ||= current_order.order_items.find(params[:order_item_id])
+

2022-01-24 14:43 UTC, n-chornyi commented on vendor/assets/javascripts/toast.min.js
> +class Toast{constructor(t){this._title=!1!==t.title&&(t.title||"Title"),console.log(this._title),this._text=t.text||"Message...",this._theme=t.theme||"default",this._autohide=t.autohide&&!0,this._int
+

2022-01-24 14:43 UTC, n-chornyi commented on vendor/assets/stylesheets/toast.min.css
> +:root{--toast-width:270px;--toast-border-radius:0.25rem;--toast-theme-default:#fff;--toast-theme-primary:#0d6efd;--toast-theme-secondary:#6c757d;--toast-theme-success:#198754;--toast-theme-danger:#dc
+

2022-01-24 16:38 UTC, merged

2022-01-25 14:07 UTC, gremax commented on spec/models/book_spec.rb
> +  end
I don't understand what this test covers? Should this method just return all books or some bestsellers? IDK

ideally should be readable like
```ruby
describe '#bestsellers' do
  before do
    order.order_items.create(book: FactoryBot.create(:book), count: 1)
  end 

  it {  expect(Book.best_sellers.size).to eq 2 }
end
```